# Generated by Django 4.0.3 on 2022-03-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
                ('body', models.TextField(blank=True, max_length=64000, null=True)),
                ('highlighted', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='placeholder-image.png', null=True, upload_to='', verbose_name='Image')),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('weight', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-weight'],
            },
        ),
    ]
